### ISSUE TITLE
Players end up killing eachother

### ISSUE THREAD

**Issue by MewBucket** [peterbozso/ror2arena#7]
At a point in the game when both me and a friend get very powerful, we both were so powerful that we ended up killing each other at the same time which ended the run, I love the concept of this mod, but it is ruined by issues like this caused by artifact of chaos

**Comment by peterbozso** [comment]
Thanks for the feedback! I agree that it's a problem. I added your thoughts to #4. I am closing this one now to keep tracking all friendly fire-related stuff there.
